# SPDX-FileCopyrightText: 2023 - 2025 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Ensure Vikunja paths exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0750"
    owner: "{{ vikunja_uid }}"
    group: "{{ vikunja_gid }}"
  with_items:
    - "{{ vikunja_base_path }}"
    - "{{ vikunja_data_path }}"
    - "{{ vikunja_database_path }}"

- name: Ensure Vikunja support files installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ item }}.j2"
    dest: "{{ vikunja_base_path }}/{{ item }}"
    mode: "0640"
    owner: "{{ vikunja_uid }}"
    group: "{{ vikunja_gid }}"
  with_items:
    - env
    - labels
  register: vikunja_support_files_result

- name: Run if self-building of Vikunja container image is not enabled
  when: "not vikunja_container_image_self_build | bool"
  block:
    - name: Ensure Vikunja container image is pulled via community.docker.docker_image
      when: devture_systemd_docker_base_container_image_pull_method == 'ansible-module'
      community.docker.docker_image:
        name: "{{ vikunja_container_image }}"
        source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
        force_source: "{{ vikunja_container_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
        force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else vikunja_container_image_force_pull }}"
      register: vikunja_container_image_pull_result
      retries: "{{ devture_playbook_help_container_retries_count }}"
      delay: "{{ devture_playbook_help_container_retries_delay }}"
      until: vikunja_container_image_pull_result is not failed

    - name: Ensure Vikunja container image is pulled via ansible.builtin.command
      when: devture_systemd_docker_base_container_image_pull_method == 'command'
      ansible.builtin.command:
        cmd: "{{ devture_systemd_docker_base_host_command_docker }} pull {{ vikunja_container_image }}"
      register: vikunja_container_image_pull_result
      retries: "{{ devture_playbook_help_container_retries_count }}"
      delay: "{{ devture_playbook_help_container_retries_delay }}"
      until: vikunja_container_image_pull_result is not failed
      changed_when: "'Downloaded newer image' in vikunja_container_image_pull_result.stdout"

- name: Run if self-building of Vikunja container image is enabled
  when: "vikunja_container_image_self_build | bool"
  block:
    - name: Ensure Vikunja repository is present on self-build
      ansible.builtin.git:
        repo: "{{ vikunja_container_image_self_build_repo }}"
        version: "{{ vikunja_container_image_self_build_repo_version }}"
        dest: "{{ vikunja_container_image_self_build_src_files_path }}"
        force: "yes"
      register: vikunja_git_pull_results

    # Invoking the `docker build` command here, instead of calling the `docker_image` Ansible module,
    # because the latter does not support BuildKit.
    # See: https://github.com/ansible-collections/community.general/issues/514
    - name: Ensure Vikunja container image is built
      ansible.builtin.shell:
        chdir: "{{ vikunja_container_image_self_build_src_files_path }}"
        cmd: |
          {{ devture_systemd_docker_base_host_command_docker }} build \
          -t "{{ vikunja_container_image_self_build_name }}" \
          -f Dockerfile \
          .
      environment:
        DOCKER_BUILDKIT: "1"
        PYTHON: "/usr/bin/python3"
      register: result
      changed_when: "'Successfully built' in result.stdout or ('writing image' in result.stderr and 'CACHED' not in result.stderr)"

- name: Ensure Vikunja container network is created via community.docker.docker_network
  when: devture_systemd_docker_base_container_network_creation_method == 'ansible-module'
  community.docker.docker_network:
    enable_ipv6: "{{ devture_systemd_docker_base_ipv6_enabled }}"
    name: "{{ vikunja_container_network }}"
    driver: bridge
    driver_options: "{{ devture_systemd_docker_base_container_networks_driver_options }}"

- name: Ensure Vikunja container network is created via ansible.builtin.command
  when: devture_systemd_docker_base_container_network_creation_method == 'command'
  ansible.builtin.command:
    cmd: >-
      {{ devture_systemd_docker_base_host_command_docker }} network create
      {% if devture_systemd_docker_base_ipv6_enabled %}--ipv6{% endif %}
      {{ devture_systemd_docker_base_container_networks_driver_options_string }}
      {{ vikunja_container_network }}
  register: network_creation_result
  changed_when: network_creation_result.rc == 0
  failed_when: network_creation_result.rc != 0 and 'already exists' not in network_creation_result.stderr

- name: Ensure Vikunja systemd service is present
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/vikunja.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ vikunja_identifier }}.service"
    mode: "0644"
  register: vikunja_systemd_service_result

- name: Determine whether Vikunja needs a restart
  ansible.builtin.set_fact:
    vikunja_restart_necessary: >-
      {{
        vikunja_support_files_result.changed | default(false)
        or vikunja_systemd_service_result.changed | default(false)
        or vikunja_container_image_pull_result.changed | default(false)
      }}
