# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Check existence of Vikunja systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ vikunja_identifier }}.service"
  register: vikunja_service_stat

- name: Uninstall Vikunja systemd services and files
  when: vikunja_service_stat.stat.exists | bool
  block:
    - name: Ensure Vikunja systemd service is stopped
      ansible.builtin.service:
        name: "{{ vikunja_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure Vikunja systemd service does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ vikunja_identifier }}.service"
        state: absent

    - name: Ensure Vikunja support files do not exist
      ansible.builtin.file:
        path: "{{ vikunja_base_path }}/{{ item }}"
        state: absent
      with_items:
        - env
        - labels

    - name: Ensure Vikunja image source files path does not exist
      ansible.builtin.file:
        path: "{{ vikunja_container_image_self_build_src_files_path }}"
        state: absent

    - name: Ensure Vikunja local data path does not exist if empty
      ansible.builtin.command:
        cmd: "rmdir {{ vikunja_data_path }}"
      register: vikunja_data_path_deletion_result
      changed_when: vikunja_data_path_deletion_result.rc == 0
      failed_when: false

    - name: Ensure Vikunja local database path does not exist if empty
      ansible.builtin.command:
        cmd: "rmdir {{ vikunja_database_path }}"
      register: vikunja_database_path_deletion_result
      changed_when: vikunja_database_path_deletion_result.rc == 0
      failed_when: false

    - name: Ensure Vikunja base path does not exist if empty
      ansible.builtin.command:
        cmd: "rmdir {{ vikunja_base_path }}"
      register: vikunja_base_path_deletion_result
      changed_when: vikunja_base_path_deletion_result.rc == 0
      failed_when: false

    - name: Ensure Vikunja container network does not exist via community.docker.docker_network
      when: devture_systemd_docker_base_container_network_creation_method == 'ansible-module'
      community.docker.docker_network:
        name: "{{ vikunja_container_network }}"
        state: absent
      register: vikunja_network_deletion_result

    - name: Ensure Vikunja container network does not exist via ansible.builtin.command
      when: devture_systemd_docker_base_container_network_creation_method == 'command'
      ansible.builtin.command:
        cmd: >-
          {{ devture_systemd_docker_base_host_command_docker }} network rm
          {{ vikunja_container_network }}
      register: vikunja_network_deletion_result
      changed_when: vikunja_container_network in vikunja_network_deletion_result.stdout

- name: Check existence of Vikunja local data path
  ansible.builtin.stat:
    path: "{{ vikunja_data_path }}"
  register: vikunja_data_path_stat

# We just want to notify the user. Deleting data is too destructive.
- name: Notify if Vikunja local data remains
  when: vikunja_data_path_stat.stat.exists | bool
  ansible.builtin.set_fact:
    devture_playbook_runtime_messages_list: |
      {{
        devture_playbook_runtime_messages_list | default([])
        +
        [
          "Note: As the local Vikunja instance has been removed, some old data remains in `" + vikunja_data_path + "`. Feel free to delete it."
        ]
      }}

- name: Check existence of Vikunja local database path
  ansible.builtin.stat:
    path: "{{ vikunja_database_path }}"
  register: vikunja_database_path_stat

# We just want to notify the user. Deleting database is too destructive.
- name: Notify if Vikunja local database remains
  when: vikunja_database_path_stat.stat.exists | bool
  ansible.builtin.set_fact:
    devture_playbook_runtime_messages_list: |
      {{
        devture_playbook_runtime_messages_list | default([])
        +
        [
          "Note: As the local Vikunja instance has been removed, some old database remains in `" + vikunja_database_path + "`. Feel free to delete it."
        ]
      }}
